name: Deploy Site

on:
  workflow_dispatch:
    inputs:
      base_path:
        description: 'Base path for the deployment'
        required: true
        type: string
        default: '/'
      destination_dir:
        description: 'Destination directory for the deployment'
        required: true
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.14.0
          run_install: true

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Override Vite Base Path
        run: |
          sed -i.bak "s|base: .*|base: '${{ inputs.base_path }}',|" vite.config.ts

      - name: Build
        run: pnpm build

      - name: Debug disk space and node version
        run: |
          df -h
          node -v
          pnpm -v

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ inputs.destination_dir }}
          keep_files: true
