name: PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        uses: ./.github/workflows/deploy.yml
        with:
          base_path: "/${{ github.event.pull_request.number }}/"
          destination_dir: "${{ github.event.pull_request.number }}"
