name: PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # The URL will be set by the GitHub Pages deployment
      url: https://${{ github.repository_owner }}.github.io/joshuahynes.com/${{ github.event.pull_request.number }}/
    
    steps:
      - name: Deploy to GitHub Pages
        uses: ./.github/workflows/deploy.yml
        with:
          base_path: "/${{ github.event.pull_request.number }}/"
          destination_dir: "${{ github.event.pull_request.number }}"
          
      - name: Get the deployment URL
        id: deployment
        run: |
          echo "page_url=https://${{ github.repository_owner }}.github.io/joshuahynes.com/${{ github.event.pull_request.number }}/" >> $GITHUB_OUTPUT
